# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: commcare-cloud tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-22.04 ]
        python-version: ["3.6", "3.10"]

    env:
      ANSIBLE_ROLES_PATH: "~/.ansible/roles"
      CI_TEST: 1
      TEST: main

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get clean
        sudo apt-get update -qq
        source control/init.sh
        # Note: the installs must be done in the following order, otherwise the installation of commcare-cloud
        # tries to install from the commcare-cloud-bootstrap.egg_info directory
        pip install -e .[test]

        # Python for deploy-stack in .tests/tests.sh
        # May be removed when this file is updated to match global_vars/all.yml:python_version
        curl -sSf --retry 5 -o python-3.9.tar.bz2 'https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/18.04/x86_64/python-3.9.tar.bz2'
        sudo tar xjf python-3.9.tar.bz2 --directory /

        # Install virtualenv as an isolated global executable for deploy-stack in .tests/tests.sh
        python3 -m pip install --user pipx
        pipx install virtualenv

    - name: Run tests
      run: |
        .tests/tests.sh
